// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using calculadora.API.Data;

namespace calculadora.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("calculadora.API.Models.Dividir", b =>
                {
                    b.Property<int>("dividirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dividirHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dividirId");

                    b.ToTable("dividir","dbo");
                });

            modelBuilder.Entity("calculadora.API.Models.Exponencial", b =>
                {
                    b.Property<int>("exponencialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("exponencialHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exponencialId");

                    b.ToTable("exponencial","dbo");
                });

            modelBuilder.Entity("calculadora.API.Models.Multiplicar", b =>
                {
                    b.Property<int>("multiplicarlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("multiplicarHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("multiplicarlId");

                    b.ToTable("multiplicar","dbo");
                });

            modelBuilder.Entity("calculadora.API.Models.Raiz", b =>
                {
                    b.Property<int>("raizlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("raizHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("raizlId");

                    b.ToTable("raiz","dbo");
                });

            modelBuilder.Entity("calculadora.API.Models.Restar", b =>
                {
                    b.Property<int>("restarlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("restarlHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("restarlId");

                    b.ToTable("restar","dbo");
                });

            modelBuilder.Entity("calculadora.API.Models.Sumar", b =>
                {
                    b.Property<int>("sumarlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sumarHistorico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sumarlId");

                    b.ToTable("sumar","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
