// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bitacora.API.Data;

namespace bitacora.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191103023734_Initial2nd")]
    partial class Initial2nd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bitacora.API.Models.Bitacora", b =>
                {
                    b.Property<int>("bitacoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("bitacoraFecha")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("bitacoraHoraFinal")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("bitacoraHoraInicio")
                        .HasColumnType("DateTime");

                    b.Property<int>("category_Id")
                        .HasColumnType("int");

                    b.HasKey("bitacoraId");

                    b.HasIndex("category_Id");

                    b.ToTable("Bitacora","dbo");
                });

            modelBuilder.Entity("bitacora.API.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Category","dbo");
                });

            modelBuilder.Entity("bitacora.API.Models.Bitacora", b =>
                {
                    b.HasOne("bitacora.API.Models.Category", "Category")
                        .WithMany("Bitacoras")
                        .HasForeignKey("category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
